import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY || '';

const ai = new GoogleGenAI({ apiKey: API_KEY });

/**
 * Generates a Minecraft-style image based on an input image.
 * @param base64Image The base64 encoded string of the source image (without data:image/... prefix)
 * @param mimeType The mime type of the image
 * @param granularity A number from 1 (coarse) to 10 (fine) representing block size.
 */
export const generateMinecraftImage = async (
  base64Image: string, 
  mimeType: string,
  granularity: number = 5
): Promise<string> => {
  try {
    if (!API_KEY) {
      throw new Error("API Key is missing");
    }

    let resolutionDescription = "";

    // REVISED SCALE LOGIC:
    // The goal is "Pixel Art" / "Mosaic".
    // Granularity now controls the "Grid Density".
    // Lower number = Larger Blocks (Lower Grid Resolution)
    // Higher number = Smaller Blocks (Higher Grid Resolution)
    
    // Default is 5. User requested this to be "one scale larger" (coarser).
    // Previous mapping: 5 was ~Large. 
    // New mapping: 5 is ~32x32 grid (Very distinct blocks).
    
    if (granularity <= 2) {
      resolutionDescription = "an extremely low-res 16x16 block grid (Abstract)";
    } else if (granularity <= 4) {
      resolutionDescription = "a low-res 24x24 block grid (Very Chunky)";
    } else if (granularity <= 6) { 
      // Default range
      resolutionDescription = "a medium-low 32x32 to 40x40 block grid (Large, Distinct Blocks)";
    } else if (granularity <= 8) {
      resolutionDescription = "a standard 64x64 block grid (Standard Pixel Art)";
    } else {
      resolutionDescription = "a high-res 100x100 block grid (Detailed)";
    }

    const prompt = `Recreate this image as a flat 2D Minecraft Map Art (Pixel Art Mosaic).
    
    STRICT VISUAL RULES:
    1. **FLAT MOSAIC**: The output must be a 2D flat grid of Minecraft blocks. NO 3D perspective. NO depth. It should look like a "Map Art" created in-game.
    2. **GRID RECONSTRUCTION**: Reconstruct the image by replacing every pixel region of the original image with a single Minecraft block texture (e.g., Wool, Concrete, Terracotta, Planks).
    3. **RESOLUTION**: The output grid density must be ${resolutionDescription}.
    4. **TEXTURE**: The individual texture of each block (the weave of wool, the grit of concrete) must be visible.
    5. **NO SMOOTHING**: Do not generate smooth lines. The image must look aliased and blocky.
    
    Output ONLY the direct 2D pixel art image. Do not include background scenery, frames, or a player character.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (parts && parts.length > 0) {
      // Check for inlineData (base64 image)
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return part.inlineData.data;
        }
      }
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};