import { GoogleGenAI, Modality } from "@google/genai";
import { AnimationStyle } from "../types";

const API_KEY = process.env.API_KEY || '';

const ai = new GoogleGenAI({ apiKey: API_KEY });

// Style-specific prompts for each animation style
const STYLE_PROMPTS: Record<AnimationStyle, string> = {
  ghibli: `Transform this image into Studio Ghibli / Hayao Miyazaki animation style:
    - Hand-drawn watercolor aesthetic with soft, dreamy quality
    - Warm, gentle color palette with natural lighting
    - Detailed backgrounds with lush nature elements
    - Expressive characters with realistic proportions
    - Emphasis on atmosphere and emotion
    - Soft edges and organic forms
    - Beautiful sky and cloud details`,
  
  disney: `Transform this image into classic Disney animation style:
    - Bright, vibrant colors with high saturation
    - Clean, smooth line work
    - Rounded, appealing character designs
    - Fairy tale aesthetic with magical elements
    - Expressive faces and body language
    - Theatrical lighting and composition
    - Optimistic and uplifting mood`,
  
  pixar: `Transform this image into Pixar 3D animation style:
    - High-quality 3D rendering with detailed textures
    - Realistic lighting and shadows
    - Rich material properties (subsurface scattering, reflections)
    - Appealing character proportions with squash and stretch
    - Expressive eyes and facial features
    - Detailed environments with depth
    - Cinematic camera angles and composition`,
  
  anime: `Transform this image into Japanese anime style:
    - Large, expressive eyes with detailed highlights
    - Sharp, clean line work with bold outlines
    - Vibrant colors with cel-shading
    - Dynamic poses and action lines
    - Exaggerated facial expressions
    - Distinctive hair with spiky or flowing style
    - Speed lines and visual effects for drama`,
  
  cartoon: `Transform this image into American cartoon style:
    - Bold, simplified shapes and forms
    - Exaggerated proportions and features
    - Bright, contrasting colors
    - Thick outlines and flat shading
    - Humorous and playful character design
    - Energetic poses and gestures
    - Comic timing and visual comedy elements`
};

/**
 * Generates an animation-style image based on an input image and selected style.
 * @param base64Image The base64 encoded string of the source image (without data:image/... prefix)
 * @param mimeType The mime type of the image
 * @param style The animation style to apply
 */
export const generateMinecraftImage = async (
  base64Image: string, 
  mimeType: string,
  style: AnimationStyle = 'ghibli'
): Promise<string> => {
  try {
    if (!API_KEY) {
      throw new Error("API Key is missing");
    }

    // Get the style-specific prompt
    const stylePrompt = STYLE_PROMPTS[style];

    const prompt = `${stylePrompt}

IMPORTANT RULES:
1. Recreate the entire scene/subject in the specified animation style
2. Maintain the core composition and subject matter
3. Apply the style's characteristic visual language consistently
4. Ensure high quality and attention to detail
5. Output ONLY the transformed image without any frames, borders, or text overlays

Create a beautiful, professional-quality transformation that captures the essence of the chosen animation style.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (parts && parts.length > 0) {
      // Check for inlineData (base64 image)
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return part.inlineData.data;
        }
      }
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};